account/urls.py
from django.contrib.auth import views
from django.urls import path
# from .views import Home
from .views import AcViews
app_name='account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    
    # path('logout/', views.LogoutView.as_view(), name='logout'),

    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns+=[
    # path('', Home, name='home'),
    path('', AcViews.as_view(), name='home'),

]

blog/urls.py
from django.db.models.fields import related
from django.urls import path,re_path
from django.conf import settings
from .views import  pashm,LiView,DetailPost,CategorList,AuthorList
app_name='blog'
urlpatterns = [
    path('av/',pashm,name='av')
    ,path('',LiView.as_view(),name='data'),
    # path('home/page/<int:page>/',baz,name='data'),
    path('home/page/<int:page>/',LiView.as_view(),name='data'),
    # re_path(r'(?P<slug>[-\w]+)-(?P<status>[-\w]+)',linkmojjazza,name='linkmojjazza')
    path('as/<slug:slug>/',DetailPost.as_view(),name='linkmojjazza'),
    # path('category/<slug:slug>/',namayeshCate,name='namayeshCate'),
    # path('category/<slug:slug>/page/<int:page>/',namayeshCate,name='namayeshCate')
    path('category/<slug:slug>/',CategorList.as_view(),name='namayeshCate'),
    path('category/<slug:slug>/page/<int:page>/',CategorList.as_view(),name='namayeshCate'),
    ########
    path('Author/<slug:UserName>',AuthorList.as_view(),name='authorU'),
    path('Author/<slug:UserName>/page/<int:page>',AuthorList.as_view(),name='authorU'),
]

second/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from blog.views import LiView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',)),
    path('',LiView),
    path('account/',include('account.urls'))
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.html import format_html
from extentions.utils import jalali_con
#manager
class PostManager(models.Manager):
    def pubadmin(self):
        return self.filter(status='publish')
class CatManager(models.Manager):
    def CategoryActive(self):
        return self.filter(status=True)

# Create your models here.

class Category(models.Model):
    title=models.CharField(max_length=256,verbose_name='عنوان')
    sluglink=models.SlugField(unique=True,max_length=22,verbose_name='آدرس دسته بندی')
    parent=models.ForeignKey('self',default=None,null=True,blank=True,on_delete=models.SET_NULL,related_name='children',verbose_name='زیر دسته')
    status=models.BooleanField(default=True,verbose_name='دیده شدن')
    position=models.IntegerField(verbose_name='پوزیشن')
    # publish=models.DateTimeField(default=timezone.now,verbose_name='زمان ارائه')    
    created=models.DateTimeField(auto_now_add=True,null=True)
    class Meta:
        verbose_name='دسته بندی'
        verbose_name_plural=' دسته بندی ها'
        ordering=('parent_id',)
    def __str__(self) -> str:
        return self.title
    def jlcreat(self):
        return jalali_con(self.created)
    jlcreat.short_description='زمان ساخت'
    objects=CatManager()
    
class Post(models.Model):
    verbose_name='یییی'
    STATUS_CHOICES=(

        ('publish','منتشر شده'),
        ('draft','آماده انتشار')
    )
    title=models.CharField(max_length=256,verbose_name='عنوان')
    sluglink=models.SlugField(unique_for_date='publish',max_length=22,verbose_name='آدرس مطلب موردنظر')
    author=models.ForeignKey(User,null=True,on_delete=models.SET_NULL,related_name="authorM",default='انتخاب کنید',verbose_name='نویسنده')
    body=models.TextField(verbose_name='محتوا')
    publish=models.DateTimeField(default=timezone.now,verbose_name='زمان ارائه')    
    created=models.DateTimeField(auto_now_add=True)
    cat=models.ManyToManyField(Category,verbose_name='دسته بندی',related_name='cat')
    updated=models.DateTimeField(auto_now=True)
    status=models.CharField(choices=STATUS_CHOICES,max_length=256,verbose_name='وضعیت',default='')
    picture=models.ImageField(upload_to='images',verbose_name='تصویر')
    class Meta:
        ordering=("-publish",)
        verbose_name='پست'
        verbose_name_plural='پست'
    def __str__(self) -> str:
        return self.title
    def jalalpub(self):
        return jalali_con(self.publish)
    jalalpub.short_description='زمان انتشار'
    def jlcreat(self):
        return jalali_con(self.created)
    jlcreat.short_description='زمان ساخت'
    objects=PostManager()
    def PictView(self):
        return format_html(f'<img width=100 src="{self.picture.url}">')

account/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.models import Post
# Create your views here.
# @login_required
# def Home(req):
#     return render(req,'registration/home.html')
class AcViews(LoginRequiredMixin,ListView):
    template_name='registration/home.html'
    queryset=Post.objects.all()
    context_object_name='data'

blog/views.py
# from django.core import paginator
from django.shortcuts import render,get_object_or_404
# from django.core.paginator import Page, Paginator
from django.http import HttpResponse, request
from .models import Post,Category
from django.views.generic import ListView,DetailView
from django.contrib.auth.models import User
# Create your views here.
def pashm(request):
    return HttpResponse('sssssssssssssssssssslammmmmmmmmmmmmmmm')
#main####
# def baz(req,page=1):
#     listmataleb=Post.objects.pubadmin()
#     paginator=Paginator(listmataleb,4)
#     # gettedad=req.GET.get('safhe')
#     mataleb=paginator.get_page(page)
#     context={
#         'mohtava':mataleb
#     }
#     return render(req,'index.html',context)
class LiView(ListView):
    model=Post
    template_name='blog/index.html'
    # queryset=Post.objects.pubadmin()
    global POSTpub
    POSTpub=Post.objects.pubadmin()
    queryset=POSTpub
    context_object_name='mohtava'
    paginate_by=4
####POst####
# def linkmojjazza(request,slug):
#     context={
#         'mohtava':get_object_or_404(Post,sluglink=slug,status='publish'),
#     }
#     return render(request,'post.html',context)
class DetailPost(DetailView):
    template_name='blog/post.html'
    context_object_name='mohtava'
    def get_object(self):
        slug=self.kwargs.get('slug')
        return get_object_or_404(POSTpub,sluglink=slug)



# def namayeshCate(request,slug,page=1):
#     cadast=get_object_or_404(Category,sluglink=slug,status=True)
#     list_safhe=cadast.cat.pubadmin()
#     paginator=Paginator(list_safhe,3)
#     matlab=paginator.get_page(page)    
#     context={
#         'category':cadast,
#         'mohtavaP':matlab

#     }
#     return render(request,'Categoryha.html',context)

class CategorList(ListView):
    queryset=Post.objects.pubadmin()
    paginate_by=1
    template_name='blog/Categoryha.html'
    context_object_name='mohtava'
    def get_queryset(self):
        # return super().get_queryset()
        global cadast
        slug=self.kwargs.get('slug')
        cadast=get_object_or_404(Category.objects.CategoryActive(),sluglink=slug)
        return cadast.cat.pubadmin()
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['category']=cadast
        return context

class AuthorList(ListView):
    template_name='blog/Author.html'
    context_object_name='mohtava'
    paginate_by=3
    def get_queryset(self):
        slug=self.kwargs.get('UserName')
        global yashmu
        yashmu=get_object_or_404(User,username=slug)
        return yashmu.authorM.pubadmin()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authorV'] =yashmu
        return context

templates/blog/Author.html
{% extends 'blog/DefView.html' %}
{% block prev_link_button %}
    {%url 'blog:authorU' authorV page_obj.previous_page_number %}
{% endblock  %}

{% block next_link_button %}
    {% url 'blog:authorU' authorV page_obj.next_page_number %}
{% endblock  %} 
{% block headerCategory %}
    <h3 class='alert alert-primary text-center'>دسته بندی {{authorV}}</h3>
{% endblock  %}

templates/blog/Categoryha.html
{% extends 'blog/DefView.html' %}

{% block prev_link_button %}
    {%url 'blog:data' page_obj.previous_page_number %}
{% endblock  %}

{% block next_link_button %}
    {% url 'blog:data' page_obj.next_page_number %}
{% endblock  %}

{% block headerCategory %}
    <h3 class='alert alert-primary text-center'>دسته بندی {{category}}</h3>
{% endblock  %}

templates/blog/DefView.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block main %}
<header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>The one and only Sky</h1>
                    <span class="subheading">developmented by Erfan Sky</span>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                {% block headerCategory %}{% endblock %}
                    {% for ins in mohtava %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'blog:linkmojjazza' ins.sluglink %}">
                            <h2 class="post-title">{{ins.title|truncatewords:5}}</h2>
                            <h3 class="post-subtitle">{{ins.body|truncatewords:20}}</h3>
                        </a>
                        <p class="post-meta">
                            نوشته شده توسط 
                            <a href="{% url 'blog:authorU' ins.author %}">{{ins.author.get_full_name}}</a>
                            
                        {{ins.jalalpub}}
                        </p>
                        <div>
                        {% for icref in ins.cat.CategoryActive %}
                        <a href='{% url "blog:namayeshCate" icref.sluglink %}'> #{{icref}},</a>
                        {% endfor %}
                        </div>
                        
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4">
                    {% if is_paginated %}
                    {% if page_obj.has_previous %}
                    <a class="btn btn-primary text-uppercase ml-3" href="{% block prev_link_button %}{% endblock  %}"> جدیدتر &rarr; </a>
                    {% endif %}
                    {% if page_obj.has_next %}
                    <a class="btn btn-primary text-uppercase" href="{% block next_link_button %}{% endblock  %}">قدیمی تر &larr; </a>
                    {% endif %}
                    
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blog/base.html
{% load static %}
{% load main_tag %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico'%}" />
        <!-- Font Awesome icons (free version)-->
        <!-- private css-->
        <link href="{% static 'css/maincss.css' %}" rel="stylesheet" />
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:data' %}">{% testtag %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {% firstinc %}
            </div>
        </nav>
        <!-- Page Header-->
        <div>
        <!-- Main Content-->
        {% block main%}
        {% endblock  %}
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/blog/inctag/navigbar.html
<div class="collapse navbar-collapse nav" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:data' %}" target="blank">خانه</a></li>
        {% for icat in categ %}
            {% if icat.parent == None %}
                <li class="nav-item">
                <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:namayeshCate' icat.sluglink %}">{{icat.title}}</a>
                    {% if icat.children.CategoryActive%}
                        <ul class="navbar-nav ms-auto py-4 py-lg-0">
                            {% for icat in icat.children.CategoryActive %}
                                <li class="nav-item">
                                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:namayeshCate' icat.sluglink %}">{{icat.title}}</a>
                                    {% if icat.children.CategoryActive%}
                                        {% include 'blog/inctag/nvai_loop.html' %}
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</div>

templates/blog/inctag/nvai_loop.html
<ul class="navbar-nav ms-auto py-4 py-lg-0">    
    {% for icat in icat.children.all %}
        <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:namayeshCate' icat.sluglink %}">{{icat.title}}</a>
        {% if icat.children.all %}
            {% include 'blog/inctag/nvai_loop.html' %}
        {% endif %}
        </li>
    {% endfor %}
</ul>

templates/blog/index.html
{% extends 'blog/DefView.html' %}

{% block prev_link_button %}
    {%url 'blog:data' page_obj.previous_page_number %}
{% endblock  %}

{% block next_link_button %}
    {% url 'blog:data' page_obj.next_page_number %}
{% endblock  %}

templates/blog/post.html
{% extends 'blog/base.html' %}
{% block title %}{{mohtava.title}} {% endblock title %}
{% load static %}
{% block main %}
    <header class="masthead" style="background-image: url('{{mohtava.picture.url}}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>{{mohtava.title}}</h1>
                        <span class="subheading">{{mohtava.jalalpub}}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {{mohtava.title}}
                    {{mohtava.body|linebreaks}}
                    {% comment %} {{mohtava.cat.all}} {% endcomment %}
                    {% for icref in mohtava.cat.CategoryActive %}
                        <a href='{% url "blog:namayeshCate" icref.sluglink %}'> #{{icref}},</a>
                    {% endfor %} 
                
                </div>
            </div>
        </div>
    </article>
{% endblock main %} 

templates/blog2/defart.html
<h1>{{mohtava.title}}</h1>
<p>{{mohtava.body}}</p>
<img src={{mohtava.picture.url}} alt='mohtava.title'>

templates/blog2/home.html
{% for i in mohtava %}
<article>
<h1><a href='{% url "blog:linkmojjazza" i.sluglink %}'>{{i.title}}</a></h1>
<p>{{i.streamer}}</p>
<img src={{i.picture.url}} alt='i.title'>
</acrticle>
{% endfor %}